# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 21:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('address', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('summary', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
