# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='abc@def.com', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
