# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-24 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomgr', '0002_auto_20170624_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
