# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomgr', '0003_auto_20170624_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile',
            field=models.CharField(default='Full Stack Developer', max_length=50),
        ),
    ]
