# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 20:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infomgr', '0004_userinfo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='abc@def.com', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('address', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('profile', models.CharField(default='Full Stack Developer', max_length=50)),
                ('skills', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume', models.TextField()),
                ('github_link', models.TextField(blank=True)),
                ('linkedin_link', models.TextField(blank=True)),
                ('twitter_link', models.TextField(blank=True)),
                ('portfolio_link', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infomgr.UserInfo'),
        ),
    ]
